#!/bin/bash
SCRIPTS_ROOT=$(readlink -f $(dirname $BASH_SOURCE))
. $SCRIPTS_ROOT/config/setup.sh

for BUILD_TYPE in $BUILD_TYPES
do
    for LIB in $LIBS
    do
        . $SCRIPTS_ROOT/config/$LIB.sh
        . $SCRIPTS_ROOT/libs/$LIB.sh
    done
done

echo "--- NON-DEFAULT BUILD ENVIDONMENT VARIABLES ---"
echo "SDK_INSTALL_PREFIX=$SDK_INSTALL_PREFIX"
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
echo "QTDIR=$QTDIR"
echo "DCMTKLIBDIR=$DCMTKLIBDIR"
echo "DCMTKINCLUDEDIR=$DCMTKINCLUDEDIR"
echo "VTKLIBDIR=$VTKLIBDIR"
echo "VTKINCLUDEDIR=$VTKINCLUDEDIR"
echo "GDCMLIBDIR=$GDCMLIBDIR"
echo "GDCMINCLUDEDIR=$GDCMINCLUDEDIR"
echo "ITKLIBDIR=$ITKLIBDIR"
echo "ITKINCLUDEDIR=$ITKINCLUDEDIR"
echo "THREADWEAVERLIBDIR=$THREADWEAVERLIBDIR"
echo "THREADWEAVERINCLUDEDIR=$THREADWEAVERINCLUDEDIR"
