if(MSVC)
    set(SDK_INSTALL_DEBUG_DIR "${CMAKE_SOURCE_DIR}/../sdk-install-debug" CACHE PATH "Directory where the Starviewer debug SDK is installed.")
    set(SDK_INSTALL_RELEASE_DIR "${CMAKE_SOURCE_DIR}/../sdk-install" CACHE PATH "Directory where the Starviewer release SDK is installed.")

    string(TOLOWER ${CMAKE_BUILD_TYPE} BUILD_TYPE)
    if(${BUILD_TYPE} STREQUAL debug AND NOT STARVIEWER_BUILD_DEBUG_WITH_RELEASE_LIBS)
        set(SDK_INSTALL_DIR ${SDK_INSTALL_DEBUG_DIR})
    else()
        set(SDK_INSTALL_DIR ${SDK_INSTALL_RELEASE_DIR})
    endif()
else()
    set(SDK_INSTALL_DIR "${CMAKE_SOURCE_DIR}/../sdk-install" CACHE PATH "Directory where the Starviewer SDK is installed.")
    set(SDK_INSTALL_RELEASE_DIR ${SDK_INSTALL_DIR})
endif()

if(WIN32)
    set(QT_LAST_DIR msvc2017_64)
elseif(APPLE)
    set(QT_LAST_DIR clang_64)
elseif(UNIX)
    set(QT_LAST_DIR gcc_64)
endif()
set(QT_DIR ${SDK_INSTALL_RELEASE_DIR}/qt/5.12.6/${QT_LAST_DIR} CACHE PATH "Directory where Qt is installed.")

set(DEPLOYMENT_REPO_DIR "${CMAKE_SOURCE_DIR}/../../starviewer-deployment" CACHE PATH "Directory of the deployment repository.")
