#!/bin/bash
SOURCE_DIR="$SDK_SOURCE_DIR_BASE/VTK-9.2.5"

CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE:STRING=$SDK_BUILD_TYPE \
               -DCMAKE_INSTALL_PREFIX:PATH=$SDK_INSTALL_PREFIX \
               -DCMAKE_PREFIX_PATH:PATH=$QTDIR \
               -DVTK_MODULE_ENABLE_VTK_GUISupportQt:STRING=YES \
               -DVTK_QT_VERSION:STRING=5"

VTKCMAKEDIR="$SDK_INSTALL_PREFIX/$LIB64DIR/cmake/vtk-9.2"
VTKLIBDIR="$SDK_INSTALL_PREFIX/$LIB64DIR"
VTKBINDIR="$SDK_INSTALL_PREFIX/bin"
VTKINCLUDEDIR="$SDK_INSTALL_PREFIX/include/vtk-9.2"
