# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/extensions/playground/volume3dviewfusedtesting
# Target is an application:  

FORMS += qvolume3dviewfusedtestingextensionbase.ui \
         qcluteditordialogbase.ui
HEADERS += volume3dviewfusedtestingextensionmediator.h \
           qvolume3dviewfusedtestingextension.h \
           qcluteditordialog.h \
           volume3dfusedviewer.h \
           vtkVolumeRayCastCompositeFunctionFx.h \
           vtkVolumeRayCastCompositeFxFunction.h \
           fusionvoxelshader.h 
SOURCES += volume3dviewfusedtestingextensionmediator.cpp \
           qvolume3dviewfusedtestingextension.cpp \
           qcluteditordialog.cpp \
           volume3dfusedviewer.cpp \
           fusionvoxelshader.cpp \
           vtkVolumeRayCastCompositeFxFunction.cxx 
RESOURCES += volume3dviewfusedtesting.qrc
include(../../basicconfextensions.inc)
